import {
  AdminUser,
  AdminTenant,
  MetricCardData,
  ActivityEvent,
  InvoiceItem,
  ApiConnector,
  AuditLogEntry,
  GenericRecord,
} from '../types/admin';

export const INITIAL_METRIC_CARDS: MetricCardData[] = [
  {
    id: 'mrr',
    title: 'Receita Recorrente Mensal (MRR)',
    value: 'R$ 148.950,00',
    changePercentage: 14.8,
    isPositiveChange: true,
    periodLabel: 'vs. mês anterior',
    badge: 'Financeiro',
    sparklineData: [92, 98, 105, 114, 122, 131, 148],
    colorScheme: 'emerald',
  },
  {
    id: 'users',
    title: 'Usuários Ativos na Plataforma',
    value: '3.420',
    changePercentage: 8.2,
    isPositiveChange: true,
    periodLabel: 'vs. semana anterior',
    badge: 'Contas',
    sparklineData: [2100, 2350, 2600, 2900, 3100, 3350, 3420],
    colorScheme: 'indigo',
  },
  {
    id: 'tenants',
    title: 'Organizações / Tenants Ativos',
    value: '42',
    changePercentage: 5.0,
    isPositiveChange: true,
    periodLabel: 'taxa de retenção: 99.1%',
    badge: 'Multi-Tenant',
    sparklineData: [32, 34, 35, 38, 39, 41, 42],
    colorScheme: 'cyan',
  },
  {
    id: 'api_uptime',
    title: 'Disponibilidade do Sistema (SLA)',
    value: '99.98%',
    changePercentage: 0.02,
    isPositiveChange: true,
    periodLabel: 'últimos 90 dias',
    badge: 'Infraestrutura',
    sparklineData: [99.9, 99.95, 99.92, 99.97, 99.98, 99.98, 99.98],
    colorScheme: 'emerald',
  },
];

export const INITIAL_CHART_REVENUE = [
  { label: 'Jan', receita: 98000, despesas: 34000, lucro: 64000 },
  { label: 'Fev', receita: 105000, despesas: 36000, lucro: 69000 },
  { label: 'Mar', receita: 112000, despesas: 38000, lucro: 74000 },
  { label: 'Abr', receita: 120000, despesas: 39000, lucro: 81000 },
  { label: 'Mai', receita: 128000, despesas: 41000, lucro: 87000 },
  { label: 'Jun', receita: 135000, despesas: 42000, lucro: 93000 },
  { label: 'Jul', receita: 142000, despesas: 43000, lucro: 99000 },
  { label: 'Ago', receita: 148950, despesas: 44200, lucro: 104750 },
];

export const INITIAL_CHART_USERS = [
  { label: 'Seg', acessos: 1420, novos: 45 },
  { label: 'Ter', acessos: 1680, novos: 52 },
  { label: 'Qua', acessos: 1950, novos: 68 },
  { label: 'Qui', acessos: 1840, novos: 49 },
  { label: 'Sex', acessos: 1720, novos: 38 },
  { label: 'Sáb', acessos: 890, novos: 15 },
  { label: 'Dom', acessos: 640, novos: 12 },
];

export const INITIAL_RECENT_ACTIVITIES: ActivityEvent[] = [
  {
    id: 'act-1',
    userId: 'u-101',
    userName: 'Carlos Silva (Super Admin)',
    action: 'Criou novo tenant',
    target: 'Prefeitura Municipal de Joinville',
    category: 'system',
    timestamp: 'Há 12 minutos',
    status: 'success',
    details: 'Tenant ID #4209102 configurado com plano Enterprise.',
  },
  {
    id: 'act-2',
    userId: 'u-102',
    userName: 'Mariana Duarte',
    action: 'Fatura liquidada via PIX',
    target: 'Invoice #INV-2026-089',
    category: 'billing',
    timestamp: 'Há 35 minutos',
    status: 'success',
    details: 'Valor: R$ 4.500,00 — Tenant: Araucária Gestão Pública.',
  },
  {
    id: 'act-3',
    userId: 'u-103',
    userName: 'Sistema Automático',
    action: 'Sincronização de Webhook',
    target: 'API Siconfi / STN Gateway',
    category: 'system',
    timestamp: 'Há 1 hora',
    status: 'info',
    details: '14.280 registros atualizados com sucesso.',
  },
  {
    id: 'act-4',
    userId: 'u-104',
    userName: 'Rafael Mendonça',
    action: 'Tentativa de login suspeita bloqueada',
    target: 'IP 187.54.12.98',
    category: 'security',
    timestamp: 'Há 2 horas',
    status: 'warning',
    details: '3 tentativas com credenciais inválidas dispararam rate limiting.',
  },
];

export const INITIAL_ADMIN_USERS: AdminUser[] = [
  {
    id: 'usr-1',
    name: 'Carlos Eduardo Silva',
    email: 'carlos.silva@sysgov.online',
    role: 'SUPER_ADMIN',
    department: 'Diretoria de Tecnologia',
    status: 'active',
    lastLoginAt: '2026-08-23 11:15',
    createdAt: '2025-01-10',
    permissions: ['users.manage', 'tenants.manage', 'billing.manage', 'system.all'],
    tenantName: 'SysGov Central',
  },
  {
    id: 'usr-2',
    name: 'Ana Beatriz Souza',
    email: 'ana.souza@sysgov.online',
    role: 'ADMIN',
    department: 'Operações & Suporte',
    status: 'active',
    lastLoginAt: '2026-08-23 10:42',
    createdAt: '2025-02-15',
    permissions: ['users.create', 'users.edit', 'tenants.manage', 'logs.view'],
    tenantName: 'SysGov Central',
  },
  {
    id: 'usr-3',
    name: 'Marcos Vinicius Ribeiro',
    email: 'marcos.ribeiro@gestaopr.gov.br',
    role: 'MANAGER',
    department: 'Secretaria de Finanças',
    status: 'active',
    lastLoginAt: '2026-08-22 17:30',
    createdAt: '2025-03-01',
    permissions: ['data.view', 'export.data', 'billing.view'],
    tenantName: 'Prefeitura de Araucária',
  },
  {
    id: 'usr-4',
    name: 'Juliana Fagundes',
    email: 'juliana.f@auditoria.com',
    role: 'OPERATOR',
    department: 'Controladoria Interna',
    status: 'active',
    lastLoginAt: '2026-08-21 14:10',
    createdAt: '2025-04-12',
    permissions: ['data.create', 'data.edit', 'data.view'],
    tenantName: 'Prefeitura de Araucária',
  },
  {
    id: 'usr-5',
    name: 'Rodrigo Antunes',
    email: 'rodrigo.antunes@consultoria.org',
    role: 'VIEWER',
    department: 'Auditoria Externa',
    status: 'pending',
    createdAt: '2026-08-20',
    permissions: ['data.view'],
    tenantName: 'Prefeitura de Campo Largo',
  },
  {
    id: 'usr-6',
    name: 'Patrícia Nogueira',
    email: 'patricia.nogueira@inativo.com',
    role: 'OPERATOR',
    department: 'Contabilidade',
    status: 'suspended',
    lastLoginAt: '2026-06-15 09:20',
    createdAt: '2025-05-18',
    permissions: [],
    tenantName: 'Prefeitura de Colombo',
  },
];

export const INITIAL_ADMIN_TENANTS: AdminTenant[] = [
  {
    id: 'tenant-01',
    name: 'Prefeitura Municipal de Araucária',
    slug: 'araucaria-pr',
    domain: 'gestao.araucaria.pr.gov.br',
    plan: 'enterprise',
    status: 'active',
    userCount: 48,
    maxUsers: 100,
    storageUsedMb: 4820,
    storageLimitMb: 20480,
    monthlyRevenue: 6500.0,
    currency: 'BRL',
    createdAt: '2025-01-15',
    ownerEmail: 'secretaria.financas@araucaria.pr.gov.br',
    customBranding: {
      portalTitle: 'Portal Integrado de Gestão — Araucária',
      primaryColor: '#10b981',
      customDomainActive: true,
    },
  },
  {
    id: 'tenant-02',
    name: 'Prefeitura Municipal de Campo Largo',
    slug: 'campo-largo-pr',
    domain: 'painel.campolargo.pr.gov.br',
    plan: 'professional',
    status: 'active',
    userCount: 22,
    maxUsers: 50,
    storageUsedMb: 2150,
    storageLimitMb: 10240,
    monthlyRevenue: 3800.0,
    currency: 'BRL',
    createdAt: '2025-03-10',
    ownerEmail: 'gabinete@campolargo.pr.gov.br',
  },
  {
    id: 'tenant-03',
    name: 'Prefeitura Municipal de Maringá',
    slug: 'maringa-pr',
    domain: 'fiscal.maringa.pr.gov.br',
    plan: 'enterprise',
    status: 'active',
    userCount: 84,
    maxUsers: 150,
    storageUsedMb: 9240,
    storageLimitMb: 51200,
    monthlyRevenue: 9200.0,
    currency: 'BRL',
    createdAt: '2025-04-02',
    ownerEmail: 'planejamento@maringa.pr.gov.br',
  },
  {
    id: 'tenant-04',
    name: 'Câmara Municipal de Fazenda Rio Grande',
    slug: 'camara-frg',
    plan: 'starter',
    status: 'trialing',
    userCount: 6,
    maxUsers: 10,
    storageUsedMb: 420,
    storageLimitMb: 2048,
    monthlyRevenue: 1450.0,
    currency: 'BRL',
    createdAt: '2026-08-10',
    ownerEmail: 'ti@camarafrg.pr.leg.br',
  },
  {
    id: 'tenant-05',
    name: 'Instituto de Previdência de Ponta Grossa',
    slug: 'prev-ponta-grossa',
    plan: 'professional',
    status: 'past_due',
    userCount: 14,
    maxUsers: 30,
    storageUsedMb: 1800,
    storageLimitMb: 5120,
    monthlyRevenue: 2900.0,
    currency: 'BRL',
    createdAt: '2025-06-20',
    ownerEmail: 'contato@prevpg.pr.gov.br',
  },
];

export const INITIAL_GENERIC_RECORDS: GenericRecord[] = [
  {
    id: 'rec-001',
    code: 'DOC-2026-089',
    title: 'Contrato de Modernização Tecnológica e Infraestrutura em Nuvem',
    category: 'Tecnologia & Inovação',
    status: 'ativo',
    priority: 'alta',
    value: 345000.0,
    assignee: 'Carlos Silva',
    createdAt: '2026-01-12',
    updatedAt: '2026-08-20',
    tags: ['SaaS', 'Cloud', 'Prioritário'],
  },
  {
    id: 'rec-002',
    code: 'DOC-2026-090',
    title: 'Relatório Bimestral de Conformidade Fiscal e Metas da LRF',
    category: 'Controladoria & Finanças',
    status: 'ativo',
    priority: 'critica',
    value: 0.0,
    assignee: 'Mariana Duarte',
    createdAt: '2026-02-14',
    updatedAt: '2026-08-22',
    tags: ['LRF', 'Oficial', 'TCE'],
  },
  {
    id: 'rec-003',
    code: 'DOC-2026-091',
    title: 'Plano Diretor de Arrecadação e Combate à Evasão Tributária',
    category: 'Planejamento Estratégico',
    status: 'em_revisao',
    priority: 'alta',
    value: 128000.0,
    assignee: 'Rafael Mendonça',
    createdAt: '2026-03-05',
    updatedAt: '2026-08-18',
    tags: ['IPTU', 'ISS', 'Arrecadação'],
  },
  {
    id: 'rec-004',
    code: 'DOC-2026-092',
    title: 'Termo de Cooperação Técnica Intermunicipal de Compartilhamento',
    category: 'Convênios & Parcerias',
    status: 'rascunho',
    priority: 'media',
    value: 45000.0,
    assignee: 'Juliana Fagundes',
    createdAt: '2026-04-18',
    updatedAt: '2026-08-10',
    tags: ['Convênio', 'Consórcio'],
  },
  {
    id: 'rec-005',
    code: 'DOC-2026-093',
    title: 'Auditoria de Despesas com Pessoal e Folha de Pagamento',
    category: 'Recursos Humanos',
    status: 'arquivado',
    priority: 'baixa',
    value: 82000.0,
    assignee: 'Marcos Vinicius',
    createdAt: '2025-11-20',
    updatedAt: '2026-05-30',
    tags: ['RH', 'Folha', 'Auditoria'],
  },
];

export const INITIAL_INVOICES: InvoiceItem[] = [
  {
    id: 'inv-101',
    invoiceNumber: 'INV-2026-0089',
    tenantId: 'tenant-01',
    tenantName: 'Prefeitura Municipal de Araucária',
    amount: 6500.0,
    currency: 'BRL',
    status: 'paid',
    issuedAt: '2026-08-01',
    dueDate: '2026-08-10',
    paidAt: '2026-08-08',
    plan: 'Plano Enterprise Custom',
  },
  {
    id: 'inv-102',
    invoiceNumber: 'INV-2026-0090',
    tenantId: 'tenant-02',
    tenantName: 'Prefeitura Municipal de Campo Largo',
    amount: 3800.0,
    currency: 'BRL',
    status: 'paid',
    issuedAt: '2026-08-01',
    dueDate: '2026-08-10',
    paidAt: '2026-08-09',
    plan: 'Plano Professional',
  },
  {
    id: 'inv-103',
    invoiceNumber: 'INV-2026-0091',
    tenantId: 'tenant-03',
    tenantName: 'Prefeitura Municipal de Maringá',
    amount: 9200.0,
    currency: 'BRL',
    status: 'paid',
    issuedAt: '2026-08-01',
    dueDate: '2026-08-15',
    paidAt: '2026-08-14',
    plan: 'Plano Enterprise Custom',
  },
  {
    id: 'inv-104',
    invoiceNumber: 'INV-2026-0092',
    tenantId: 'tenant-05',
    tenantName: 'Instituto de Previdência de Ponta Grossa',
    amount: 2900.0,
    currency: 'BRL',
    status: 'overdue',
    issuedAt: '2026-08-01',
    dueDate: '2026-08-10',
    plan: 'Plano Professional',
  },
  {
    id: 'inv-105',
    invoiceNumber: 'INV-2026-0093',
    tenantId: 'tenant-04',
    tenantName: 'Câmara Municipal de Fazenda Rio Grande',
    amount: 1450.0,
    currency: 'BRL',
    status: 'pending',
    issuedAt: '2026-08-20',
    dueDate: '2026-08-30',
    plan: 'Plano Starter',
  },
];

export const INITIAL_API_CONNECTORS: ApiConnector[] = [
  {
    id: 'api-1',
    name: 'Siconfi / STN Gateway Fiscal',
    endpoint: 'https://apidatalake.tesouro.gov.br/ords/siconfi/tt/',
    type: 'REST',
    status: 'operational',
    uptimePercent: 99.98,
    latencyMs: 142,
    lastSyncAt: 'Há 4 minutos',
    requests24h: 48920,
    errorRatePercent: 0.04,
  },
  {
    id: 'api-2',
    name: 'Portal Nacional de Contratações Públicas (PNCP)',
    endpoint: 'https://pncp.gov.br/api/consulta/v1/',
    type: 'REST',
    status: 'operational',
    uptimePercent: 99.91,
    latencyMs: 210,
    lastSyncAt: 'Há 12 minutos',
    requests24h: 32410,
    errorRatePercent: 0.12,
  },
  {
    id: 'api-3',
    name: 'Transferegov / SICONV Repasses',
    endpoint: 'https://api.convenios.gov.br/siconv/v1/',
    type: 'REST',
    status: 'operational',
    uptimePercent: 99.85,
    latencyMs: 320,
    lastSyncAt: 'Há 25 minutos',
    requests24h: 18200,
    errorRatePercent: 0.28,
  },
  {
    id: 'api-4',
    name: 'Tribunal de Contas do Estado (TCE-PR Sync)',
    endpoint: 'https://servicos.tce.pr.gov.br/api/v2/',
    type: 'WEBHOOK',
    status: 'operational',
    uptimePercent: 99.95,
    latencyMs: 95,
    lastSyncAt: 'Há 8 minutos',
    requests24h: 12450,
    errorRatePercent: 0.01,
  },
  {
    id: 'api-5',
    name: 'Banco Central do Brasil / Focus & Índices',
    endpoint: 'https://olinda.bcb.gov.br/olinda/servico/PTAX/versao/v1/',
    type: 'REST',
    status: 'operational',
    uptimePercent: 100.0,
    latencyMs: 82,
    lastSyncAt: 'Há 15 minutos',
    requests24h: 8400,
    errorRatePercent: 0.0,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-001',
    timestamp: '2026-08-23 11:24:18',
    level: 'INFO',
    service: 'AuthService',
    actor: {
      id: 'usr-1',
      name: 'Carlos Silva',
      email: 'carlos.silva@sysgov.online',
      ipAddress: '177.135.88.12',
    },
    event: 'USER_LOGIN_SUCCESS',
    targetResource: 'Session #sess_99218',
    statusCode: 200,
  },
  {
    id: 'log-002',
    timestamp: '2026-08-23 11:12:05',
    level: 'SUCCESS',
    service: 'TenantManager',
    actor: {
      id: 'usr-1',
      name: 'Carlos Silva',
      email: 'carlos.silva@sysgov.online',
      ipAddress: '177.135.88.12',
    },
    event: 'TENANT_PROVISIONED',
    targetResource: 'Tenant #tenant-04 (camara-frg)',
    payload: { plan: 'starter', maxUsers: 10 },
    statusCode: 201,
  },
  {
    id: 'log-003',
    timestamp: '2026-08-23 10:45:30',
    level: 'WARN',
    service: 'RateLimiter',
    actor: {
      id: 'anon',
      name: 'Anonymous Client',
      email: 'unauthenticated',
      ipAddress: '187.54.12.98',
    },
    event: 'RATE_LIMIT_EXCEEDED',
    targetResource: 'Endpoint /api/v1/auth/login',
    payload: { attempts: 5, threshold: 5 },
    statusCode: 429,
  },
  {
    id: 'log-004',
    timestamp: '2026-08-23 09:30:12',
    level: 'INFO',
    service: 'BillingEngine',
    actor: {
      id: 'system',
      name: 'System Cron Worker',
      email: 'cron@sysgov.online',
      ipAddress: '10.0.4.15',
    },
    event: 'INVOICE_GENERATED',
    targetResource: 'Invoice #INV-2026-0093',
    payload: { amount: 1450.0, tenantId: 'tenant-04' },
    statusCode: 200,
  },
  {
    id: 'log-005',
    timestamp: '2026-08-22 18:22:45',
    level: 'ERROR',
    service: 'WebhookDispatcher',
    actor: {
      id: 'system',
      name: 'Webhook Worker',
      email: 'worker@sysgov.online',
      ipAddress: '10.0.4.22',
    },
    event: 'WEBHOOK_DELIVERY_FAILED',
    targetResource: 'Webhook #wh_88192 (Endpoint unreachable 504)',
    payload: { retryCount: 3, timeoutMs: 5000 },
    statusCode: 504,
  },
];
