// @generated by scripts/generate-module-registry.js
// Re-exporta o registry gerado automaticamente

export {
  MODULE_REGISTRY,
  getModuleById,
  getEnabledModules,
  getModuleRoute,
} from './moduleRegistry.generated';
export type { ModuleDefinition } from './moduleRegistry.generated';
