// @generated by scripts/generate-module-registry.js
// NÃO EDITE MANUALMENTE — execute `npm run generate:registry` para atualizar

import React, { lazy } from 'react';
import { ModulePlaceholder } from '@/components/ModulePlaceholder';
const DashboardComponent = lazy(() => import('@/modules/dashboard/DashboardModule'));
const OrgComponent = lazy(() => import('@/modules/orgchart/OrgChartModule'));
const ProcurementComponent = lazy(() => import('@/modules/procurement/ProcurementModule'));
const ContractsComponent = lazy(() => import('@/modules/contracts/ContractsModule'));
const FinanceComponent = lazy(() => import('@/modules/finance/FinanceModule'));
const PedagogicoComponent = lazy(() => import('@/modules/pedagogico/PedagogicoModule'));
const RhComponent = lazy(() => import('@/modules/rh/RhModule'));
const CemiteriosComponent = lazy(() => import('@/modules/cemiterios/CemiteriosModule'));
const UsersComponent = lazy(() => import('@/modules/access/AccessManagement'));
const MenuManagerComponent = lazy(() => import('@/modules/access/MenuManager'));
const ModuleGranularityComponent = lazy(() => import('@/modules/access/ModuleGranularityManager'));
const PermissionMatrixComponent = lazy(() => import('@/modules/access/PermissionMatrix'));
const ClientComponent = lazy(async () => ({ default: () => React.createElement(ModulePlaceholder, { name: "Client", alias: "client", description: "Funcionalidades do cliente/tenant do SYSGOV" }) }));
const LicitaComponent = lazy(() => import('@/modules/licita/LicitaModule'));
const TestmoduleComponent = lazy(async () => ({ default: () => React.createElement(ModulePlaceholder, { name: "TestModule", alias: "testmodule", description: "Módulo de negócio TestModule para a plataforma SYSGOV" }) }));

export interface ModuleDefinition {
  id: string;
  name: string;
  component: React.LazyExoticComponent<React.ComponentType<any>>;
  routePath?: string;
  routes?: string[];
  requiredPermission?: string;
  isAdminOnly?: boolean;
  icon?: string;
}

export const MODULE_REGISTRY: Record<string, ModuleDefinition> = {
  dashboard: {
    id: 'dashboard',
    name: "Gabinete do Prefeito",
    component: DashboardComponent,
    routePath: '',
    routes: ["","dashboard"],
    requiredPermission: 'dashboard.view',
    icon: 'LayoutDashboard',
  },
  org: {
    id: 'org',
    name: "Estrutura Organizacional",
    component: OrgComponent,
    routePath: 'organograma',
    routes: ["organograma","org"],
    requiredPermission: 'org.view',
    icon: 'Building2',
  },
  procurement: {
    id: 'procurement',
    name: "Licitações & Compras",
    component: ProcurementComponent,
    routePath: 'licitacoes',
    routes: ['licitacoes'],
    requiredPermission: 'procurement.view',
    icon: 'FileCheck',
  },
  contracts: {
    id: 'contracts',
    name: "Contratos Administrativos",
    component: ContractsComponent,
    routePath: 'contratos',
    routes: ['contratos'],
    requiredPermission: 'contracts.view',
    icon: 'Handshake',
  },
  finance: {
    id: 'finance',
    name: "Gestão Financeira & Orçamentária",
    component: FinanceComponent,
    routePath: 'financeiro',
    routes: ['financeiro'],
    requiredPermission: 'finance.view',
    icon: 'DollarSign',
  },
  pedagogico: {
    id: 'pedagogico',
    name: "Gestão Pedagógica",
    component: PedagogicoComponent,
    routePath: 'pedagogico',
    routes: ['pedagogico'],
    requiredPermission: 'pedagogico.view',
    icon: 'BookOpen',
  },
  rh: {
    id: 'rh',
    name: "Recursos Humanos",
    component: RhComponent,
    routePath: 'rh',
    routes: ['rh'],
    requiredPermission: 'rh.view',
    icon: 'Users',
  },
  cemiterios: {
    id: 'cemiterios',
    name: "Gestão de Cemitérios",
    component: CemiteriosComponent,
    routePath: 'cemiterios',
    routes: ['cemiterios'],
    requiredPermission: 'cemiterios.view',
    icon: 'Shield',
  },
  users: {
    id: 'users',
    name: "Usuários & Acessos",
    component: UsersComponent,
    routePath: 'usuarios',
    routes: ['usuarios'],
    requiredPermission: 'users.manage',
    icon: 'ShieldCheck',
  },
  menuManager: {
    id: 'menuManager',
    name: "Gerenciador de Menus",
    component: MenuManagerComponent,
    routePath: 'gerenciar-menus',
    routes: ['gerenciar-menus'],
    requiredPermission: '',
    isAdminOnly: true,
    icon: 'Settings2',
  },
  moduleGranularity: {
    id: 'moduleGranularity',
    name: "Granularidade de Módulos",
    component: ModuleGranularityComponent,
    routePath: 'granularidade-módulos',
    routes: ["granularidade-módulos","granularidade-modulos"],
    requiredPermission: '',
    isAdminOnly: true,
    icon: 'Shield',
  },
  permissionMatrix: {
    id: 'permissionMatrix',
    name: "Matriz de Permissões",
    component: PermissionMatrixComponent,
    routePath: 'matriz-permissoes',
    routes: ['matriz-permissoes'],
    requiredPermission: '',
    isAdminOnly: true,
    icon: 'Shield',
  },
  client: {
    id: 'client',
    name: "Client",
    component: ClientComponent,
    routePath: 'client',
    routes: ['client'],
    requiredPermission: 'client.view',
    icon: 'Layers',
  },
  licita: {
    id: 'licita',
    name: "Licita",
    component: LicitaComponent,
    routePath: 'licita',
    routes: ['licita'],
    requiredPermission: 'licita.view',
    icon: 'FileText',
  },
  testmodule: {
    id: 'testmodule',
    name: "TestModule",
    component: TestmoduleComponent,
    routePath: 'testmodule',
    routes: ['testmodule'],
    requiredPermission: 'testmodule.view',
    icon: 'Layers',
  }
};

export function getModuleById(id: string): ModuleDefinition | undefined {
  return MODULE_REGISTRY[id];
}

export function getEnabledModules(): ModuleDefinition[] {
  return Object.values(MODULE_REGISTRY);
}

export function getModuleRoute(id: string): string {
  const mod = MODULE_REGISTRY[id];
  if (!mod) return '/';
  if (mod.routePath === '') return '/';
  return mod.routePath ? `/${mod.routePath}` : `/${id}`;
}
